spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/digiarchive?serverTimezone=UTC
    username: root
    password: adminbeel
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: '@project.name@'
  jpa:
    open-in-view: false
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format-sql: true
        use-sql-coments: true
        generate-statistics: false
    show-sql: true
management:
  endpoints:
    web:
      application:
  version: '@project.version@'
  timezone: ${user.timezone}

server:
  port: 8080
  ssl:
    enabled: false

